#include "src/transfer/brpc_channel.h"

#ifdef FALCONKV_HAS_BRPC

#include <brpc/channel.h>
#include <brpc/controller.h>

#include <cstring>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <netdb.h>

#include "src/common/logging.h"

namespace falconkv {

struct BrpcChannel::Impl {
    brpc::Channel channel;
    bool connected = false;
};

BrpcChannel::BrpcChannel() : impl_(std::make_unique<Impl>()) {}

BrpcChannel::~BrpcChannel() {
    Disconnect();
}

Status BrpcChannel::Connect(const std::string& addr) {
    if (addr.empty()) {
        LOG(ERROR) << "[BrpcChannel] Connect: empty address";
        return Status::InvalidArg("empty address");
    }

    // Pre-check TCP reachability before initializing brpc channel,
    // since brpc::Channel::Init connects lazily and always succeeds.
    {
        auto colon = addr.rfind(':');
        if (colon == std::string::npos) {
            LOG(ERROR) << "[BrpcChannel] Connect: invalid address format: " << addr;
            return Status::InvalidArg("invalid address format: " + addr);
        }
        std::string host = addr.substr(0, colon);
        int port = std::stoi(addr.substr(colon + 1));

        int sock = socket(AF_INET, SOCK_STREAM, 0);
        if (sock < 0) {
            LOG(ERROR) << "[BrpcChannel] Connect: failed to create socket: " << strerror(errno);
            return Status::RpcError("failed to create socket");
        }

        struct sockaddr_in sa;
        std::memset(&sa, 0, sizeof(sa));
        sa.sin_family = AF_INET;
        sa.sin_port = htons(static_cast<uint16_t>(port));

        if (inet_pton(AF_INET, host.c_str(), &sa.sin_addr) <= 0) {
            struct hostent* he = gethostbyname(host.c_str());
            if (!he) {
                close(sock);
                LOG(ERROR) << "[BrpcChannel] Connect: cannot resolve host: " << host;
                return Status::RpcError("cannot resolve host: " + host);
            }
            std::memcpy(&sa.sin_addr, he->h_addr_list[0], he->h_length);
        }

        // Set send timeout on the socket for the connect attempt.
        struct timeval tv;
        tv.tv_sec = 1;
        tv.tv_usec = 0;
        setsockopt(sock, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));

        int rc = ::connect(sock, reinterpret_cast<struct sockaddr*>(&sa), sizeof(sa));
        close(sock);

        if (rc != 0) {
            LOG(ERROR) << "[BrpcChannel] Connect: cannot connect to " << addr
                       << ": " << strerror(errno);
            return Status::RpcError(std::string("cannot connect to ") + addr);
        }
    }

    brpc::ChannelOptions options;
    options.connect_timeout_ms = 3000;
    options.timeout_ms = 5000;
    options.max_retry = 3;

    int rc = impl_->channel.Init(addr.c_str(), &options);
    if (rc != 0) {
        LOG(ERROR) << "[BrpcChannel] Connect: failed to init brpc channel to "
                   << addr << ", rc=" << rc;
        return Status::RpcError(std::string("failed to init brpc channel to ") + addr);
    }

    impl_->connected = true;
    return Status::OK();
}

void BrpcChannel::Disconnect() {
    if (impl_) {
        impl_->connected = false;
    }
}

bool BrpcChannel::IsConnected() const {
    return impl_ && impl_->connected;
}

Status BrpcChannel::SyncCall(const std::string& method,
                              const std::string& /*request_data*/,
                              std::string* /*response_data*/) {
    if (!IsConnected()) {
        return Status::RpcError("not connected");
    }
    // RPC method dispatch requires brpc service stubs generated by the brpc
    // protobuf plugin. Until those are available, all RPC calls return
    // NotSupported.
    return Status::NotSupported(std::string("RPC method not available: ") + method);
}

Status BrpcChannel::AsyncCall(const std::string& method,
                               const std::string& request_data,
                               RpcCallback* callback) {
    std::string response_data;
    Status s = SyncCall(method, request_data, &response_data);
    if (callback) {
        callback->OnComplete(s);
    }
    return s;
}

Status BrpcChannel::WriteData(const std::string& /*addr*/, uint64_t /*offset*/,
                               const void* /*data*/, uint32_t /*size*/) {
    if (!IsConnected()) {
        return Status::RpcError("not connected");
    }
    // Requires brpc service stubs for FalconKVStoreService.
    return Status::NotSupported("WriteData RPC not yet available");
}

Status BrpcChannel::ReadData(const std::string& /*addr*/, uint64_t /*offset*/,
                              void* /*buffer*/, uint32_t /*size*/) {
    if (!IsConnected()) {
        return Status::RpcError("not connected");
    }
    return Status::NotSupported("ReadData RPC not yet available");
}

Status BrpcChannel::BatchWriteData(const std::string& /*addr*/,
                                    const std::vector<IoSegment>& /*segments*/) {
    if (!IsConnected()) {
        return Status::RpcError("not connected");
    }
    return Status::NotSupported("BatchWriteData RPC not yet available");
}

Status BrpcChannel::BatchReadData(const std::string& /*addr*/,
                                   const std::vector<IoSegment>& /*segments*/) {
    if (!IsConnected()) {
        return Status::RpcError("not connected");
    }
    return Status::NotSupported("BatchReadData RPC not yet available");
}

} // namespace falconkv

#else // !FALCONKV_HAS_BRPC

namespace falconkv {

struct BrpcChannel::Impl {
    bool connected = false;
};

BrpcChannel::BrpcChannel() : impl_(std::make_unique<Impl>()) {}
BrpcChannel::~BrpcChannel() = default;

Status BrpcChannel::Connect(const std::string&) {
    return Status::NotSupported("brpc not available");
}

void BrpcChannel::Disconnect() {}
bool BrpcChannel::IsConnected() const { return false; }

Status BrpcChannel::SyncCall(const std::string&, const std::string&, std::string*) {
    return Status::NotSupported("brpc not available");
}

Status BrpcChannel::AsyncCall(const std::string&, const std::string&, RpcCallback*) {
    return Status::NotSupported("brpc not available");
}

Status BrpcChannel::WriteData(const std::string&, uint64_t, const void*, uint32_t) {
    return Status::NotSupported("brpc not available");
}

Status BrpcChannel::ReadData(const std::string&, uint64_t, void*, uint32_t) {
    return Status::NotSupported("brpc not available");
}

Status BrpcChannel::BatchWriteData(const std::string&, const std::vector<IoSegment>&) {
    return Status::NotSupported("brpc not available");
}

Status BrpcChannel::BatchReadData(const std::string&, const std::vector<IoSegment>&) {
    return Status::NotSupported("brpc not available");
}

} // namespace falconkv

#endif // FALCONKV_HAS_BRPC
